import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdtempSync,symlinkSync,linkSync,chmodSync,rmSync} from 'node:fs';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
const root='/workspace/Project-Cortex', base=resolve(root,'_goals/convex-backend-runtime-2026-10-02/qa/task03-foundation-live-preparation');
const g=await import(pathToFileURL(resolve(base,'scripts/guard.mjs')));
const {authDenial,rememberPlatformWire}=await import(pathToFileURL(resolve(base,'scripts/native-engine.mjs')));
const {ConvexError}=await import('convex/values');
g.sourcePreflight();const freeze=JSON.parse(readFileSync(resolve(base,'runtime-freeze.json')));
const candidateSha256=g.sha256(readFileSync(resolve(base,'runtime-freeze.json')));
const ledger=JSON.parse(readFileSync(resolve(base,'path-ledger.json'))),native=JSON.parse(readFileSync(resolve(base,'native-registration-schemas.json')));
assert.equal(ledger.cases.length,259);assert.equal(new Set(ledger.cases.map(r=>r.path)).size,259);
assert.equal(ledger.cases.filter(r=>r.visibility==='public').length,200);assert.equal(ledger.cases.filter(r=>r.visibility==='internal').length,59);
const modules=new Map();for(const row of ledger.cases){const url=pathToFileURL(resolve(root,row.source)).href;if(!modules.has(url))modules.set(url,await import(url));const fn=modules.get(url)[row.path.split(':')[1]];assert.equal(fn['is'+row.kind[0].toUpperCase()+row.kind.slice(1)],true);assert.equal(Boolean(fn.isInternal),row.visibility==='internal');assert.deepEqual(JSON.parse(fn.exportArgs()),native.rows.find(r=>r.path===row.path).args);}
let negativeControls=0;
const request=JSON.parse(readFileSync(resolve(g.fixture,'project-request.json'))),target={...request,requestSha256:g.sha256(JSON.stringify(request)),kind:'cloud',deploymentType:'dev',active:true,retired:false,deleted:false,isolationVerified:true,productionDeployment:false,sharedCiTarget:false,projectId:100,createdAt:new Date().toISOString(),deploymentName:'offline-only-123',deploymentUrl:'https://offline-only-123.convex.cloud'},values={CONVEX_DEPLOY_KEY:'dev:offline-only-123|placeholder',CONVEX_DEPLOYMENT:'dev:offline-only-123',CONVEX_URL:'https://offline-only-123.convex.cloud'};
g.validateTarget(target,request,values);
for(const patch of [{operation:'bad'},{requestSha256:'bad'},{projectName:'bad'},{projectSlug:'bad'},{projectId:0},{deploymentType:'prod'},{kind:'local'},{active:false},{retired:true},{deleted:true},{isolationVerified:false},{productionDeployment:true},{sharedCiTarget:true},{deploymentUrl:'https://foreign.convex.cloud'},{privateEnvironmentFile:'bad'},{deploymentName:'efficient-ox-979'},{createdAt:'invalid'}]){assert.throws(()=>g.validateTarget({...target,...patch},request,values));negativeControls++;}
for(const inherited of [{CONVEX_URL:'https://foreign.convex.cloud'},{CONVEX_DEPLOYMENT:'prod:foreign'},{CONVEX_DEPLOY_KEY:'dev:foreign|placeholder'},{CONVEX_OVERRIDE_ACCESS_TOKEN:'placeholder'},{CONVEX_SELF_HOSTED_URL:'https://foreign.invalid'},{CONVEX_SELF_HOSTED_ADMIN_KEY:'placeholder'}]){assert.throws(()=>g.validateTarget(target,request,values,inherited));negativeControls++;}
for(const value of [{...values,OPENAI_API_KEY:'placeholder'},{...values,CONVEX_DEPLOY_KEY:'prod:offline-only-123|placeholder'}]){assert.throws(()=>g.validateTarget(target,request,value));negativeControls++;}
assert.throws(()=>g.preparationReviewed());negativeControls++;
const dir=mkdtempSync(resolve(root,'work/resume/current-guard-prep-judge/canonical-'));
try{const file=resolve(dir,'private.json');writeFileSync(file,'{}',{mode:0o600});g.canonical(file,root,true);symlinkSync(file,resolve(dir,'alias'));assert.throws(()=>g.canonical(resolve(dir,'alias'),root,true));negativeControls++;linkSync(file,resolve(dir,'hardlink'));assert.throws(()=>g.canonical(file,root,true));negativeControls++;rmSync(resolve(dir,'hardlink'));chmodSync(file,0o644);assert.throws(()=>g.canonical(file,root,true));negativeControls++;assert.throws(()=>g.canonical(resolve(dir,'missing'),root,true));negativeControls++;assert.throws(()=>g.canonical(dir+'/../other',root));negativeControls++;}finally{rmSync(dir,{recursive:true});}
for(const code of ['FORBIDDEN','UNAUTHENTICATED'])authDenial(undefined,new ConvexError({version:1,code,message:code==='FORBIDDEN'?'Access denied':'Verified identity required',retryable:false,outcome:'not_dispatched'}));
const platformWire=JSON.stringify({code:'InvalidAuth',message:'Could not authenticate JWT'});assert.equal(rememberPlatformWire(401,platformWire),true);authDenial(undefined,new Error(platformWire));
for(const [status,body]of [[200,platformWire],[401,JSON.stringify({code:'BadRequest',message:'InvalidAuth'})],[401,JSON.stringify({code:'InvalidAuth',message:'Server Error Uncaught provider failure'})]]){assert.equal(rememberPlatformWire(status,body),false);negativeControls++;}
for(const error of [new Error('ArgumentValidationError: Unauthenticated'),new Error('Could not find public function: Unauthenticated'),new Error('network FORBIDDEN'),new Error('DENIED'),new ConvexError({code:'INVALID_INPUT'}),new ConvexError({code:'UNKNOWN'}),new Error('unknown provider failure'),new Error('Private provider diagnostic Unauthenticated memory secret'),new Error('Server Error: private provider could not authenticate')]){assert.throws(()=>authDenial(undefined,error));negativeControls++;}
for(const data of [{code:'FORBIDDEN'},{code:'FORBIDDEN',message:'Private fixture resource payload'},{code:'FORBIDDEN',message:'Access denied',secret:'private'},{version:1,code:'FORBIDDEN',message:'Access denied',retryable:true,outcome:'not_dispatched'}]){assert.throws(()=>authDenial(undefined,new ConvexError(data)));negativeControls++;}
const {validateRetirement}=await import(pathToFileURL(resolve(base,'scripts/management-contract.mjs')));
const ownership={operation:request.operation,requestSha256:g.sha256(JSON.stringify(request)),id:123,slug:request.projectSlug,requestedName:request.projectName,startedAt:new Date().toISOString(),deploymentName:'offline-owned-123'},project={id:123,slug:request.projectSlug,name:request.projectName},deployment={name:'offline-owned-123',projectId:123,kind:'cloud',deploymentType:'dev',deploymentUrl:'https://offline-owned-123.convex.cloud'};
assert.equal(validateRetirement(request,ownership,project,[deployment],deployment).provisionState,'REQUEST_OWNED_PARTIAL_RECOVERY');
for(const patch of [{operation:'foreign'},{requestSha256:'foreign'},{id:456},{requestedName:'shared'},{startedAt:'invalid'},{deploymentName:'foreign-owned-123'}]){assert.throws(()=>validateRetirement(request,{...ownership,...patch},project,[deployment],deployment));negativeControls++;}
for(const patch of [{kind:'self-hosted'},{deploymentType:'prod'},{projectId:456},{deploymentUrl:'https://foreign.convex.cloud'}]){assert.throws(()=>validateRetirement(request,ownership,project,[{...deployment,...patch}],{...deployment,...patch}));negativeControls++;}
assert.throws(()=>validateRetirement(request,ownership,project,[deployment,{...deployment,name:'foreign-prod-123',deploymentType:'prod'}],deployment));negativeControls++;
const {ProcessOwner}=await import(pathToFileURL(resolve(base,'scripts/process-owner.mjs')));
const owner=new ProcessOwner();for(const [args,timeout]of [[['-e','process.exitCode=7'],3000],[['-e',"import('node:child_process').then(({spawn})=>{spawn(process.execPath,['-e','setInterval(()=>{},1000)'],{stdio:'inherit'});process.exit(0)})"],350],[['-e','setInterval(()=>{},1000)'],200],[['-e',"process.stdout.write('x'.repeat(270000));setInterval(()=>{},1000)"],3000]]){const result=await owner.run(args,{cwd:root},timeout);assert.equal(owner.records.size,0);assert.ok(result.code!==0||result.timedOut||result.overflow);}
assert.equal(owner.verifiedGroups,4);
assert.equal(g.sha256(readFileSync(resolve(base,'runtime-freeze.json'))),candidateSha256);
console.log(JSON.stringify({status:'PASS',scope:'INDEPENDENT_OFFLINE_PREPARATION_ONLY',candidateSha256,freezeFiles:freeze.files.length,nativeRegistrations:259,negativeControls,terminalProcessGroups:owner.verifiedGroups,serviceCalls:0,signatures:0}));
