# Cortex Documentation Site Configuration

# Site settings
title: "Cortex Documentation"
description: "Plug'n'play persistent memory for AI agents, powered by Convex"
baseurl: "/cortex" # Change this to match your repo name if different
url: "https://saintnick1214.github.io/Project-Cortex"

# Repository information
repository: SaintNick1214/Project-Cortex
github_username: SaintNick1214

# Theme settings
theme: jekyll-theme-cayman
# Alternative themes you can try:
# theme: jekyll-theme-minimal
# theme: jekyll-theme-architect
# theme: jekyll-theme-slate
# theme: jekyll-theme-modernist

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Plugin configuration
plugins:
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-github-metadata

# Relative links configuration
relative_links:
  enabled: true
  collections: false

# Optional front matter
optional_front_matter:
  remove_originals: false

# Titles from headings
titles_from_headings:
  enabled: true
  strip_title: true
  collections: false

# Include/Exclude files
include:
  - Documentation
  - README.md
  - CHANGELOG.md
  - CONTRIBUTING.md
  - CODE_OF_CONDUCT.md
  - SECURITY.md
  - LICENSE.md

exclude:
  - Quickstarts
  - "Internal Docs"
  - node_modules
  - vendor
  - .git
  - .gitignore
  - .github
  - scripts
  - "*.json"
  - "*.js"
  - "*.ts"

# Navigation (optional - for themes that support it)
navigation:
  - title: Home
    url: /
  - title: Documentation
    url: /Documentation/00-README
  - title: Getting Started
    url: /Documentation/01-getting-started/01-introduction
  - title: API Reference
    url: /Documentation/03-api-reference/02-memory-operations
  - title: Contributing
    url: /CONTRIBUTING
  - title: GitHub
    url: https://github.com/SaintNick1214/cortex

# Google Analytics (optional - add your tracking ID)
# google_analytics: UA-XXXXXXXXX-X

# Social links
social:
  github: SaintNick1214/cortex
  # twitter: cortexmemory
  # discord: your-discord-invite

# Footer
footer_text: |
  Built with ❤️ for the AI agent community by <a href="https://github.com/SaintNick1214">Nicholas Geil</a> / <a href="https://saintnick.ai">Saint Nick LLC</a>
