/**
 * Environment file generator
 */

import fs from 'fs-extra';
import path from 'path';
import type { WizardConfig } from './types.js';
import pc from 'picocolors';

/**
 * Generate .env.local file based on wizard configuration
 */
export function generateEnvFile(config: WizardConfig): string {
  let env = `# Cortex Memory SDK Configuration
# Generated by create-cortex-memories on ${new Date().toISOString()}

# =============================================================================
# Convex Configuration
# =============================================================================
`;

  // Add Convex configuration based on setup type
  if (config.convexSetupType === 'local') {
    env += `# Local Development
LOCAL_CONVEX_URL=http://127.0.0.1:3210
LOCAL_CONVEX_DEPLOYMENT=anonymous:anonymous-${config.projectName}
CONVEX_URL=http://127.0.0.1:3210
`;
  } else {
    env += `# Convex Cloud
CONVEX_URL=${config.convexUrl || ''}
`;
    if (config.deployKey) {
      env += `CONVEX_DEPLOY_KEY=${config.deployKey}
`;
    }
  }

  // Add graph database configuration if enabled
  if (config.graphEnabled && config.graphType !== 'skip') {
    env += `
# =============================================================================
# Graph Database Configuration (Optional)
# =============================================================================
NEO4J_URI=${config.graphUri || 'bolt://localhost:7687'}
NEO4J_USERNAME=${config.graphUsername || 'neo4j'}
NEO4J_PASSWORD=${config.graphPassword || 'cortex-password'}
`;
  }

  env += `
# =============================================================================
# OpenAI API Key (Optional - for embeddings)
# =============================================================================
# OPENAI_API_KEY=sk-...

`;

  return env;
}

/**
 * Write .env.local file to project
 */
export async function createEnvFile(
  projectPath: string,
  config: WizardConfig
): Promise<void> {
  const envPath = path.join(projectPath, '.env.local');
  const envContent = generateEnvFile(config);

  // Check if .env.local already exists
  if (fs.existsSync(envPath)) {
    const backupPath = path.join(projectPath, `.env.local.backup.${Date.now()}`);
    console.log(pc.yellow('⚠️  Existing .env.local detected'));
    console.log(pc.dim(`   Backing up to ${path.basename(backupPath)}`));
    await fs.move(envPath, backupPath);
  }

  await fs.writeFile(envPath, envContent);
  console.log(pc.green('   ✓ Created .env.local'));
}

/**
 * Create docker-compose.yml for local graph database
 */
export async function createGraphDockerCompose(
  projectPath: string,
  graphType: 'neo4j' | 'memgraph'
): Promise<void> {
  const dockerComposePath = path.join(projectPath, 'docker-compose.graph.yml');

  let dockerCompose = '';

  if (graphType === 'neo4j') {
    dockerCompose = `version: '3.8'

services:
  neo4j:
    image: neo4j:5-community
    container_name: cortex-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/cortex-password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
`;
  } else if (graphType === 'memgraph') {
    dockerCompose = `version: '3.8'

services:
  memgraph:
    image: memgraph/memgraph-platform:latest
    container_name: cortex-memgraph
    ports:
      - "7687:7687"  # Bolt
      - "3000:3000"  # Memgraph Lab
      - "7444:7444"  # Memgraph Lab secure
    environment:
      - MEMGRAPH="--log-level=TRACE"
    volumes:
      - memgraph_data:/var/lib/memgraph
      - memgraph_logs:/var/log/memgraph
    restart: unless-stopped

volumes:
  memgraph_data:
  memgraph_logs:
`;
  }

  await fs.writeFile(dockerComposePath, dockerCompose);
  console.log(pc.dim(`   Created docker-compose.graph.yml for ${graphType}`));
}

