/**
 * Environment file generator
 *
 * Generates .env.local and docker-compose files for init wizard.
 */

import fs from "fs-extra";
import path from "path";
import type { WizardConfig } from "./types.js";
import pc from "picocolors";

/**
 * Generate .env.local file content based on wizard configuration
 */
export function generateEnvFile(config: WizardConfig): string {
  let env = `# Cortex Memory SDK Configuration
# Generated by cortex init on ${new Date().toISOString()}

# =============================================================================
# Convex Configuration
# =============================================================================
`;

  // Add Convex configuration based on setup type
  if (config.convexSetupType === "local") {
    env += `# Local Development
LOCAL_CONVEX_URL=http://127.0.0.1:3210
LOCAL_CONVEX_DEPLOYMENT=anonymous:anonymous-${config.projectName}
CONVEX_URL=http://127.0.0.1:3210
`;
  } else {
    env += `# Convex Cloud
CONVEX_URL=${config.convexUrl || ""}
`;
    if (config.deployKey) {
      env += `CONVEX_DEPLOY_KEY=${config.deployKey}
`;
    }
  }

  // Add graph database configuration if enabled
  if (config.graphEnabled && config.graphType !== "skip") {
    env += `
# =============================================================================
# Graph Database Configuration (Optional)
# =============================================================================
NEO4J_URI=${config.graphUri || "bolt://localhost:7687"}
NEO4J_USERNAME=${config.graphUsername || "neo4j"}
NEO4J_PASSWORD=${config.graphPassword || "cortex-password"}
`;
  }

  env += `
# =============================================================================
# OpenAI API Key (Optional - for embeddings)
# =============================================================================
# OPENAI_API_KEY=sk-...

`;

  return env;
}

/**
 * Write .env.local file to project
 *
 * IMPORTANT: If Convex CLI has already created .env.local (with CONVEX_URL,
 * CONVEX_DEPLOYMENT, etc.), we preserve those lines and only add our
 * additional configuration (graph DB, OpenAI, etc.)
 */
export async function createEnvFile(
  projectPath: string,
  config: WizardConfig,
): Promise<void> {
  const envPath = path.join(projectPath, ".env.local");

  // Check if .env.local already exists (likely created by convex dev)
  let existingContent = "";
  let hasExistingConvexConfig = false;

  try {
    existingContent = await fs.readFile(envPath, "utf-8");
    // Check if Convex has already configured this file
    hasExistingConvexConfig =
      existingContent.includes("CONVEX_URL=") ||
      existingContent.includes("CONVEX_DEPLOYMENT=");
  } catch {
    // File doesn't exist, will create new
  }

  if (hasExistingConvexConfig) {
    // Preserve the Convex-generated content, just add our header and optional extras
    console.log(pc.dim("   Preserving Convex configuration in .env.local"));

    // Add header if not present
    let finalContent = existingContent;
    if (!existingContent.includes("# Cortex Memory SDK Configuration")) {
      finalContent = `# Cortex Memory SDK Configuration
# Generated by cortex init on ${new Date().toISOString()}

${existingContent}`;
    }

    // Add OpenAI placeholder if not present
    if (!existingContent.includes("OPENAI_API_KEY")) {
      finalContent += `
# =============================================================================
# OpenAI API Key (Optional - for embeddings)
# =============================================================================
# OPENAI_API_KEY=sk-...
`;
    }

    await fs.writeFile(envPath, finalContent);
    console.log(pc.green("   Updated .env.local"));
  } else {
    // No existing Convex config, create fresh file
    const envContent = generateEnvFile(config);

    // Backup any existing file first
    try {
      const backupPath = path.join(
        projectPath,
        `.env.local.backup.${Date.now()}`,
      );
      await fs.move(envPath, backupPath);
      console.log(pc.yellow("   Existing .env.local backed up"));
      console.log(pc.dim(`   Backed up to ${path.basename(backupPath)}`));
    } catch (error: unknown) {
      const err = error as { code?: string };
      if (err.code !== "ENOENT") {
        throw error;
      }
    }

    await fs.writeFile(envPath, envContent);
    console.log(pc.green("   Created .env.local"));
  }
}

/**
 * Append graph database configuration to existing .env.local
 * Called after Convex deployment which may have modified .env.local
 */
export async function appendGraphEnvVars(
  projectPath: string,
  config: {
    graphUri: string;
    graphUsername: string;
    graphPassword: string;
  },
): Promise<void> {
  const envPath = path.join(projectPath, ".env.local");

  const graphEnvVars = `
# =============================================================================
# Graph Database Configuration
# =============================================================================
NEO4J_URI=${config.graphUri}
NEO4J_USERNAME=${config.graphUsername}
NEO4J_PASSWORD=${config.graphPassword}
`;

  try {
    // Read existing content
    let existingContent = "";
    try {
      existingContent = await fs.readFile(envPath, "utf-8");
    } catch {
      // File doesn't exist, will create new
    }

    // Check if graph vars already exist
    if (existingContent.includes("NEO4J_URI=")) {
      console.log(pc.dim("   Graph env vars already present in .env.local"));
      return;
    }

    // Append graph vars
    await fs.writeFile(envPath, existingContent + graphEnvVars);
    console.log(pc.green("   Added graph database env vars to .env.local"));
  } catch {
    console.warn(
      pc.yellow("   Warning: Could not update .env.local with graph config"),
    );
    console.log(pc.dim(`   Please add manually:\n${graphEnvVars}`));
  }
}

/**
 * Create docker-compose.yml for local graph database
 */
export async function createGraphDockerCompose(
  projectPath: string,
  graphType: "neo4j" | "memgraph",
): Promise<void> {
  const dockerComposePath = path.join(projectPath, "docker-compose.graph.yml");

  let dockerCompose = "";

  if (graphType === "neo4j") {
    dockerCompose = `services:
  neo4j:
    image: neo4j:5-community
    container_name: cortex-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/cortex-password
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs:
`;
  } else if (graphType === "memgraph") {
    dockerCompose = `services:
  memgraph:
    image: memgraph/memgraph-platform:latest
    container_name: cortex-memgraph
    ports:
      - "7687:7687"  # Bolt
      - "3000:3000"  # Memgraph Lab
      - "7444:7444"  # Memgraph Lab secure
    environment:
      - MEMGRAPH="--log-level=TRACE"
    volumes:
      - memgraph_data:/var/lib/memgraph
      - memgraph_logs:/var/log/memgraph
    restart: unless-stopped

volumes:
  memgraph_data:
  memgraph_logs:
`;
  }

  await fs.writeFile(dockerComposePath, dockerCompose);
  console.log(pc.dim(`   Created docker-compose.graph.yml for ${graphType}`));
}
