/** Parent-run native qualifier. Requires fresh reviewed freeze and parent publication receipts. */
import assert from 'node:assert/strict';
import {ConvexHttpClient} from 'convex/browser';
import {makeFunctionReference} from 'convex/server';
import {resolve} from 'node:path';
import {readFileSync} from 'node:fs';
import {randomUUID} from 'node:crypto';
import {livePreflight,root,scratch,json,limits,Journal,sha256,exclusive,sourcePreflight,reserveTicket} from './guard.mjs';
import {boundedBody,peer} from './peer.mjs';
import {track,ownedSnapshot,allocateRows,ownershipCounts} from './ownership.mjs';
import {definitions,scenario,canonical,request} from './cases.mjs';
export function shape(value,schema){switch(schema.type){case'any':return true;case'string':return typeof value==='string';case'id':return typeof value==='string'&&value.length>0;case'number':return typeof value==='number'&&Number.isFinite(value);case'boolean':return typeof value==='boolean';case'null':return value===null;case'literal':return value===schema.value;case'array':return Array.isArray(value)&&value.every(x=>shape(x,schema.value));case'union':return schema.value.some(s=>shape(value,s));case'object':return value!==null&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).every(k=>Object.hasOwn(schema.value,k))&&Object.entries(schema.value).every(([k,v])=>value[k]===undefined?v.optional===true:shape(value[k],v.fieldType));case'record':return value!==null&&typeof value==='object'&&!Array.isArray(value);default:throw Error('QA_VALIDATOR_UNSUPPORTED');}}
export async function session(phase){const {target,values,publication}=livePreflight(phase);const parent=json(resolve(scratch,'identities.json'),scratch,true);if(parent.operation!==target.operation||parent.runId!==json(resolve(root,'project-request.json')).runId||!/^admission-[a-f0-9]{32}$/.test(parent.runId)||Object.keys(parent.identities).sort().join(',')!=='expiredJWT,foreign,forgedJWT,noJWT,ungranted,wrongAudience,wrongIssuer')throw Error('QA_IDENTITIES');
 let rpc=0,cleanupRpc=0,active=0;const start=Date.now(),journal=new Journal(parent.runId,target.operation);const clients=[];const wire=new Set();
 const boundedFetch=async(url,options)=>{if(new URL(url).origin!==target.deploymentUrl)throw Error('QA_ORIGIN');const response=await fetch(url,{...options,redirect:'error',signal:AbortSignal.timeout(limits.rpcMs)});const body=await boundedBody(response);if([400,401,403].includes(response.status)){try{const envelope=JSON.parse(body);if(['InvalidAuth','Unauthenticated','InvalidAuthHeader','NoAuthProvider'].includes(envelope.code)&&typeof envelope.message==='string'&&Object.keys(envelope).every(k=>['code','message'].includes(k)))wire.add(body);}catch{}}
 return new Response(body,{status:response.status,statusText:response.statusText,headers:response.headers});};
 const create=jwt=>{const client=new ConvexHttpClient(target.deploymentUrl,{logger:false,fetch:boundedFetch});if(jwt)client.setAuth(jwt);clients.push(client);return client;};const operator=create();operator.setAdminAuth(values.CONVEX_DEPLOY_KEY);
 const s={runId:parent.runId,target,parent,publication,journal,peerCalls:0,peerEffects:0,peerOther:0,profile:json(resolve(root,'profile.json')),async rpc(type,path,args,client=operator){if(++rpc>limits.rpc||Date.now()-start>limits.qualifierMs||++active>limits.concurrency)throw Error('QA_RPC_BUDGET');if(path.startsWith('qualificationOwned:cleanup')){if(++cleanupRpc>limits.cleanupRpc)throw Error('QA_CLEANUP_BUDGET');await reserveTicket('cleanup',limits.cleanupRpc);}await reserveTicket('native',limits.nativeClientRpc);const begun=Date.now();try{sourcePreflight();wire.clear();const value=await client[type](makeFunctionReference(path),args);if(Buffer.byteLength(JSON.stringify(value))>limits.resultBytes)throw Error('QA_RESULT_BYTES');if(value?.createdRefs)track(value.createdRefs,'created',target.operation);if(value?.deletedRefs)track(value.deletedRefs,'deleted',target.operation);if(path==='qualificationOwned:snapshot')track(ownedSnapshot(value,parent.runId),'created',target.operation);journal.append({phase,caseId:path.replace(':','-'),status:'PASS',observedCategory:'rpc-complete',elapsedMs:Date.now()-begun});return value;}catch(error){journal.append({phase,caseId:path.replace(':','-'),status:'FAIL',observedCategory:'rpc-rejected',failureClass:error?.data?.code&&/^[A-Z_]+$/.test(error.data.code)?error.data.code.toLowerCase():'native_or_transport'});throw error;}finally{active--;}}
 ,create,authDenied(error){return ['FORBIDDEN','UNAUTHENTICATED'].includes(error?.data?.code)||wire.has(error?.message);},counts:()=>({rpc,cleanupRpc,peerEffects:s.peerEffects,peerOther:s.peerOther,...ownershipCounts()}),close:()=>journal.close()};return s;}
export async function security(s){await allocateRows('security',15,s.target.operation);const inventory=json(resolve(root,'registration-inventory.json'));const publicRows=inventory.registrations.filter(r=>r.visibility==='public');assert.equal(publicRows.length,200);const bundle=json(resolve(scratch,'public-arguments.json'),scratch,true);if(bundle.operation!==s.target.operation||bundle.inventorySha256!==sha256(readFileSync(resolve(root,'registration-inventory.json')))||Object.keys(bundle.arguments).sort().join('|')!==publicRows.map(r=>r.path).sort().join('|'))throw Error('QA_ARGUMENT_BINDING');
 const foreignSeed=await s.rpc('mutation','qualificationOwned:seed',{run:s.runId,caseId:'security-foreign',subject:s.runId+'-security-foreign'});const healthy=await s.rpc('mutation','qualificationOwned:seed',{run:s.runId,caseId:'security-owner',subject:s.runId+'-security-owner'});const owner=s.create(s.parent.ownerJWT);if(!s.parent.ownerJWT)throw Error('QA_HEALTHY_IDENTITY_REQUIRED');const healthyArgs={tenantId:healthy.reference.tenantId,memorySpaceId:healthy.reference.memorySpaceId,namespace:s.runId+'-metadata',key:'healthy'};await s.rpc('mutation','mutable:set',{...healthyArgs,value:'healthy'},owner);const healthyResult=await s.rpc('query','mutable:get',healthyArgs,owner);assert.equal(healthyResult.value,'healthy');s.journal.append({phase:'security',caseId:'healthy-authenticated-public',status:'PASS',observedCategory:'nonempty-public-control'});
 for(const row of publicRows){const args=bundle.arguments[row.path];assert.equal(shape(args,row.args),true,'native argument shape');const before=canonical(await s.rpc('query','qualificationOwned:snapshot',{run:s.runId}));for(const identity of ['noJWT','forgedJWT','wrongIssuer','wrongAudience','expiredJWT','ungranted','foreign']){const client=s.create(s.parent.identities[identity]);await assert.rejects(()=>s.rpc(row.type,row.path,args,client),error=>s.authDenied(error));s.journal.append({phase:'security',caseId:row.path.replace(':','-'),status:'PASS',observedCategory:'authorization-denied'});}assert.equal(canonical(await s.rpc('query','qualificationOwned:snapshot',{run:s.runId})),before);s.journal.append({phase:'security',caseId:row.path.replace(':','-'),status:'PASS',noEffect:true,observedCategory:'whole-state-equal'});}
 // Actual publication tuple/args comparison supplied by parent official apiSpec, not absence-based claims.
 const actual=s.publication.functions;if(!Array.isArray(actual))throw Error('QA_APISPEC');const exact=new Map(actual.map(row=>[row.path,row]));for(const row of inventory.registrations){const seen=exact.get(row.path);assert.ok(seen);assert.equal(seen.visibility,row.visibility);assert.equal(seen.type,row.type);}
 const reader=s.create(s.parent.readerJWT);for(const row of inventory.registrations.filter(r=>r.visibility==='internal'))for(const client of [s.create(),reader])await assert.rejects(()=>s.rpc(row.type,row.path,bundle.internalArguments[row.path],client),error=>s.authDenied(error));
 for(const table of ['runtimeModelPolicies','runtimeModelQualifications','runtimeBudgetAccounts','runtimeModelOperations','runtimeModelAttempts'])for(const path of ['listTable','deleteRecord','clearTable','countTable']){const args={table,...(path==='deleteRecord'?{id:bundle.modelAttemptId}:{})};const before=canonical(await s.rpc('query','qualificationOwned:snapshot',{run:s.runId}));await assert.rejects(()=>s.rpc(['listTable','countTable'].includes(path)?'query':'mutation','admin:'+path,args),error=>!s.authDenied(error)&&/ArgumentValidationError|Value does not match validator/.test(String(error)));assert.equal(canonical(await s.rpc('query','qualificationOwned:snapshot',{run:s.runId})),before);}
 for(const credential of [undefined,'wrong-secret','malformed'])await peer(s,'public-denial',credential,403);await peer(s,'public-denial',undefined,403,s.parent.ownerJWT);const peerConfiguration=json(resolve(scratch,'peer-config.json'),scratch,true);if(peerConfiguration.operation!==s.target.operation||typeof peerConfiguration.peerSecret!=='string'||peerConfiguration.peerSecret.length<32||peerConfiguration.peerSecret.length>128)throw Error('QA_PEER_CONFIGURATION');await peer(s,'public-denial',peerConfiguration.peerSecret,403,undefined,s.runId+'-foreign');assert.deepEqual(await s.rpc('query','qualificationPeer:counter',{run:s.runId,dispatchDigest:sha256('public-denial')}),{requestCount:0,effectCount:0});
}
export async function qualify(s,phase){let complete=false,status='FAIL';try{if(phase==='synthetic'){for(const [id,kind]of definitions){sourcePreflight();if(kind==='window'){// Start within the last half of a real minute; scheduling wait is separate from window-observation wait.
 const scheduleDeadline=Date.now()+30000;while(Date.now()%60000<30000&&Date.now()<scheduleDeadline)await new Promise(done=>setTimeout(done,250));}
 const expectedCase=json(resolve(root,'cases.json')).scenarios.find(row=>row.id===id);await allocateRows(id,expectedCase.maximumCommittedCreatedRows,s.target.operation);const scenarioBefore=s.counts().rpc;await scenario(s,id,kind);if(s.counts().rpc-scenarioBefore>expectedCase.rpcCeiling)throw Error('QA_CASE_RPC_BUDGET');s.journal.append({phase:'case',caseId:id,status:'PASS',observedCategory:'outcome-asserted'});await s.rpc('query','qualificationOwned:snapshot',{run:s.runId});await s.rpc('mutation','qualificationOwned:cleanup',{run:s.runId});const left=await s.rpc('query','qualificationOwned:snapshot',{run:s.runId});assert.equal(left.filter(x=>x.row.tenantId?.startsWith(s.runId+'-')||x.row.subject?.startsWith(s.runId+'-')||x.row.run===s.runId||x.row.root?.manifestId==='qa-task04-synthetic-v1').length,0);}
 await security(s);
 }else{await allocateRows('empty',12,s.target.operation);const seeded=await s.rpc('mutation','qualificationOwned:seed',{run:s.runId,caseId:'empty-root',subject:s.runId+'-empty-root'});await s.rpc('mutation','qualificationOwned:fabricateRoot',{run:s.runId});const forgedBefore=canonical(await s.rpc('query','qualificationOwned:snapshot',{run:s.runId}));await assert.rejects(()=>s.rpc('mutation','runtimeModelPolicy:ensureBudget',{reference:seeded.reference,operationKey:'agent.respond',requestId:'forged-root',requestCanonical:canonical({text:'hello'})}),e=>e.data?.code==='CAPABILITY_UNAVAILABLE');assert.equal(canonical(await s.rpc('query','qualificationOwned:snapshot',{run:s.runId})),forgedBefore);for(const manifestId of ['qa-task04-synthetic-v1','unknown']){const before=canonical(await s.rpc('query','qualificationOwned:snapshot',{run:s.runId}));await assert.rejects(()=>s.rpc('mutation','runtimeModelPolicy:installDeploymentPolicy',{manifestId,expectedRevision:1}),e=>e.data?.code==='CAPABILITY_UNAVAILABLE');assert.equal(canonical(await s.rpc('query','qualificationOwned:snapshot',{run:s.runId})),before);}}
 status='PASS';}finally{for(let attempt=0;attempt<2&&!complete;attempt++){await s.rpc('query','qualificationOwned:snapshot',{run:s.runId});await s.rpc('mutation','qualificationOwned:cleanup',{run:s.runId});const rows=await s.rpc('query','qualificationOwned:snapshot',{run:s.runId});complete=!rows.some(x=>x.row.tenantId?.startsWith(s.runId+'-')||x.row.subject?.startsWith(s.runId+'-')||x.row.run===s.runId||x.row.root?.manifestId==='qa-task04-synthetic-v1');}s.journal.append({phase:'final',caseId:'native-qualifier',status:status==='PASS'&&complete?'PASS':'FAIL',cleanupComplete:complete,counts:s.counts()});s.close();}return {status,cleanupComplete:complete,counts:s.counts()};}
if(process.argv[1]?.endsWith('driver.mjs')){const phase=process.argv[2];if(!['synthetic','empty'].includes(phase))throw Error('QA_PHASE');const s=await session(phase);const result=await qualify(s,phase);exclusive(resolve(scratch,'result-'+phase+'-'+randomUUID()+'.json'),result);process.stdout.write(JSON.stringify(result)+'\n');process.exitCode=result.status==='PASS'&&result.cleanupComplete?0:1;}
