import {readFileSync,writeFileSync,lstatSync,realpathSync,readdirSync,openSync,writeSync,fsyncSync,closeSync} from 'node:fs';
import {resolve,dirname,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash,randomUUID} from 'node:crypto';
import {parseEnv} from 'node:util';
export const root=resolve(dirname(fileURLToPath(import.meta.url)),'..'),repo=resolve(root,'../../../..'),fixture=resolve(root,'fixture');
export const scratch=resolve(repo,'work/backend-runtime/task04-native-admission-c1');
export const sha256=v=>createHash('sha256').update(v).digest('hex');
export const limits=Object.freeze({rpc:3000,nativeClientRpc:2991,nestedNativeInvocations:9,cleanupRpc:256,concurrency:4,qualifierMs:1200000,driverMs:1440000,rpcMs:12000,scenarios:64,rows:320,storage:0,peerEffects:8,peerOther:24,resultBytes:256000,evidenceBytes:8388608,receiptBytes:16384,journalBytes:4096,journalRows:6000,processes:6,groups:2,cliMs:120000});
export function canonical(path,base,privateFile=false){if(path!==resolve(path)||!path.startsWith(base+sep)&&path!==base)throw Error('QA_PATH');let part=sep;
 for(const component of path.split(sep).filter(Boolean)){part=resolve(part,component);const s=lstatSync(part);if(s.isSymbolicLink()||realpathSync(part)!==part)throw Error('QA_PATH');}
 const s=lstatSync(path);if(s.isFile()&&s.nlink!==1)throw Error('QA_LINK');if(privateFile&&(!s.isFile()||s.uid!==process.getuid()||(s.mode&511)!==384))throw Error('QA_PRIVATE');return path;}
export function json(path,base=root,privateFile=false){return JSON.parse(readFileSync(canonical(path,base,privateFile),'utf8'));}
export function exclusive(path,value,privateFile=true,maxBytes=limits.resultBytes){canonical(dirname(path),repo);const encoded=JSON.stringify(value,null,2)+'\n';if(Buffer.byteLength(encoded)>maxBytes)throw Error('QA_BYTES');const fd=openSync(path,'wx',privateFile?0o600:0o644);try{writeSync(fd,encoded);fsyncSync(fd);}finally{closeSync(fd);}}
function operationalPaths(directory=root,prefix=''){return readdirSync(directory,{withFileTypes:true}).flatMap(entry=>{const path=prefix+entry.name;if(entry.isSymbolicLink())throw Error('QA_PATH');if(entry.isDirectory())return ['scripts','fixture'].includes(path.split('/')[0])?operationalPaths(resolve(directory,entry.name),path+'/'):[];return path.startsWith('scripts/')||path.startsWith('fixture/')||['project-request.json','cases.json','source-inventory.json','registration-inventory.json','schema-evidence.json','profile.json'].includes(path)?[path]:[];}).sort();}
export function sourcePreflight(){const frozen=json(resolve(root,'runtime-freeze.json'));if(JSON.stringify(operationalPaths())!==JSON.stringify(frozen.operationalPaths))throw Error('QA_SOURCE_INVENTORY_DRIFT');for(const row of frozen.files){if(sha256(readFileSync(canonical(resolve(root,row.path),root)))!==row.sha256)throw Error('QA_SOURCE_DRIFT');}
 const inventory=json(resolve(root,'source-inventory.json'));for(const row of inventory.acceptedGateHashes){if(sha256(readFileSync(canonical(resolve(repo,row.path),repo)))!==row.sha256)throw Error('QA_ACCEPTED_SOURCE_DRIFT');}for(const row of inventory.files){if(row.kind==='baseline-generated-not-native-codegen')continue;if(sha256(readFileSync(canonical(resolve(repo,row.source),repo)))!==row.sha256)throw Error('QA_PRODUCT_DRIFT');}
 return frozen;}
export function reviewed(){const freeze=sourcePreflight(),review=json(resolve(scratch,'preparation-review.json'),scratch,true);if(review.independent!==true||review.verdict!=='PASS'||review.freezeSha256!==sha256(readFileSync(resolve(root,'runtime-freeze.json'))))throw Error('QA_REVIEW');return freeze;}
export function validateTarget(target,request,values,inherited={}){if(target.operation!==request.operation||target.requestSha256!==sha256(JSON.stringify(request))||target.purpose!=='task04-native-admission-c1'||target.projectSlug!==request.projectSlug||target.projectName!==request.projectName||!/^cortex-task04-admission-disposable-[a-f0-9]{12}$/.test(target.projectSlug)||!Number.isSafeInteger(target.projectId)||target.projectId<=0||target.kind!=='cloud'||target.deploymentType!=='dev'||target.productionDeployment!==false||target.sharedCiTarget!==false||target.isolationVerified!==true||target.active!==true||target.retired!==false||target.deleted!==false||target.deploymentUrl!==`https://${target.deploymentName}.convex.cloud`||['admired-walrus-730','efficient-ox-979','fiery-setter-784'].includes(target.deploymentName)||target.projectId===3138249||target.privateEnvironmentFile!==request.privateEnvironmentFile)throw Error('QA_TARGET');
 if(Object.keys(values).sort().join(',')!=='CONVEX_DEPLOYMENT,CONVEX_DEPLOY_KEY,CONVEX_URL'||values.CONVEX_DEPLOYMENT!==`dev:${target.deploymentName}`||values.CONVEX_URL!==target.deploymentUrl||!values.CONVEX_DEPLOY_KEY?.startsWith(`dev:${target.deploymentName}|`)||values.CONVEX_DEPLOY_KEY.length<=`dev:${target.deploymentName}|`.length)throw Error('QA_SELECTOR');
 for(const name of ['CONVEX_DEPLOYMENT_TOKEN','CONVEX_OVERRIDE_ACCESS_TOKEN','CONVEX_SELF_HOSTED_URL','CONVEX_SELF_HOSTED_ADMIN_KEY'])if(inherited[name])throw Error('QA_SELECTOR');for(const name of Object.keys(values))if(inherited[name]&&inherited[name]!==values[name])throw Error('QA_SELECTOR');return target;}
export function livePreflight(phase){reviewed();canonical(scratch,repo);const s=lstatSync(scratch);if(s.uid!==process.getuid()||(s.mode&511)!==448)throw Error('QA_PRIVATE');if(readdirSync(scratch).some(name=>/^retirement-.*\.json$/.test(name)))throw Error('QA_RETIRED');
 const request=json(resolve(root,'project-request.json')),target=json(resolve(scratch,'target.json'),scratch,true),values=parseEnv(readFileSync(canonical(resolve(scratch,'deploy.env'),scratch,true),'utf8'));validateTarget(target,request,values,process.env);
 if(phase){const publication=json(resolve(scratch,`publication-${phase}.json`),scratch,true);if(publication.operation!==target.operation||publication.phase!==phase||publication.status!=='PASS'||publication.officialCodegen!==true||publication.typecheck!=='enable'||publication.freezeSha256!==sha256(readFileSync(resolve(root,'runtime-freeze.json'))))throw Error('QA_PUBLICATION');
 const expected=phase==='synthetic'?json(resolve(root,'divergence.json')).syntheticSha256:json(resolve(root,'divergence.json')).productionSha256;if(publication.bootstrapSha256!==expected)throw Error('QA_BOOTSTRAP');for(const row of publication.generated){if(!/^convex\/_generated\/[a-zA-Z0-9._-]+$/.test(row.path)||sha256(readFileSync(canonical(resolve(scratch,'deploy-'+phase,row.path),scratch)))!==row.sha256)throw Error('QA_CODEGEN');}
 if(!['api','server','dataModel'].every(name=>publication.generated.some(row=>new RegExp('/'+name+'(?:\\.d)?\\.(ts|js)$').test(row.path))))throw Error('QA_CODEGEN');return {target,values,publication};}return {target,values};}
const safeKeys=new Set(['version','operation','runId','phase','caseId','sequence','previousDigest','sourceDigest','fixtureDigest','bootstrapDigest','apiSpecDigest','targetReceiptDigest','startedAt','observedAt','elapsedMs','status','expectedCategory','observedCategory','counts','noEffect','cleanupComplete','processTerminal','exitCode','failureClass','receiptDigest']);
export function safeReceipt(value){if(!value||typeof value!=='object'||Object.keys(value).some(k=>!safeKeys.has(k)))throw Error('QA_RECEIPT');if(value.status!==undefined&&!['PASS','FAIL','BLOCKED','NOT_RUN'].includes(value.status))throw Error('QA_STATUS');for(const [key,v]of Object.entries(value)){if(key==='counts'){if(!v||Object.values(v).some(n=>!Number.isSafeInteger(n)||n<0))throw Error('QA_RECEIPT');}else if(typeof v==='string'){if(v.length>256||/Bearer |\n|[A-Za-z0-9_-]{20,}\.[A-Za-z0-9_-]{20,}\./.test(v))throw Error('QA_RECEIPT');}else if(typeof v!=='boolean'&&!Number.isSafeInteger(v))throw Error('QA_RECEIPT');}if(Buffer.byteLength(JSON.stringify(value))>limits.receiptBytes)throw Error('QA_RECEIPT_BYTES');return value;}
export class Journal{constructor(runId,operation){this.runId=runId;this.operation=operation;this.globalRowsInitial=0;this.globalBytesInitial=0;for(const name of readdirSync(scratch).filter(name=>/^journal-.*\.jsonl$/.test(name))){const data=readFileSync(resolve(scratch,name),'utf8');if(!data.endsWith('\n'))throw Error('QA_PARTIAL_JOURNAL');this.globalRowsInitial+=data.split('\n').length-1;this.globalBytesInitial+=Buffer.byteLength(data);}this.sequence=0;this.previous='0'.repeat(64);this.bytes=0;this.fd=openSync(resolve(scratch,`journal-${runId}-${randomUUID()}.jsonl`),'wx',0o600);}
 append(event){const value=safeReceipt({version:1,operation:this.operation,runId:this.runId,sequence:++this.sequence,previousDigest:this.previous,...event});const body=JSON.stringify(value);if(Buffer.byteLength(body)>limits.journalBytes||this.globalRowsInitial+this.sequence>limits.journalRows||this.globalBytesInitial+this.bytes+Buffer.byteLength(body)+128>limits.evidenceBytes)throw Error('QA_JOURNAL_BUDGET');const digest=sha256(body);const line=JSON.stringify({...value,receiptDigest:digest})+'\n';writeSync(this.fd,line);fsyncSync(this.fd);this.bytes+=Buffer.byteLength(line);this.previous=digest;return value;}
 close(){closeSync(this.fd);}}
/** Shared process-safe append-only dispatch tickets; unknown lock state fails closed. */
export async function reserveTicket(kind,max){if(!['native','cleanup','peer-effect','peer-other','process'].includes(kind)||!Number.isSafeInteger(max)||max<1)throw Error('QA_TICKET');const lock=resolve(scratch,'dispatch-budget.lock');const deadline=Date.now()+12000;let fd;while(fd===undefined){try{fd=openSync(lock,'wx',0o600);}catch(error){if(error.code!=='EEXIST'||Date.now()>=deadline)throw Error('QA_BUDGET_LOCK');await new Promise(done=>setTimeout(done,10));}}
 try{if(kind==='native'){const window=resolve(scratch,'qualifier-window.json');if(!lstatSync(window,{throwIfNoEntry:false}))exclusive(window,{startedAt:new Date().toISOString(),deadlineMs:1200000});const recorded=json(window,scratch,true);if(Date.now()-Date.parse(recorded.startedAt)>=1200000||recorded.deadlineMs!==1200000)throw Error('QA_TOTAL_TIME_BUDGET');}const count=readdirSync(scratch).filter(name=>name.startsWith('ticket-'+kind+'-')).length;if(count>=max)throw Error('QA_TOTAL_BUDGET');const path=resolve(scratch,`ticket-${kind}-${String(count+1).padStart(4,'0')}.json`);exclusive(path,{kind,sequence:count+1,observedAt:new Date().toISOString()});}finally{closeSync(fd);const {unlinkSync}=await import('node:fs');unlinkSync(lock);}}
