/** Credential-free AST/import graph + actual registration/schema introspection. */
import {readFileSync,readdirSync,writeFileSync} from 'node:fs';
import {resolve,relative,dirname} from 'node:path';
import ts from 'typescript';
import {build} from 'esbuild';
import {pathToFileURL} from 'node:url';
import {root,repo,fixture,sha256,exclusive} from './guard.mjs';
export async function inventory(destination){const sourceInventory=JSON.parse(readFileSync(resolve(root,'source-inventory.json')));const registrations=[],imports=[],callers=[],unknown=[];
 for(const row of [...sourceInventory.files.filter(row=>row.source.startsWith('convex-dev/')&&!row.source.includes('/_generated/')), ...['qualificationOwned.ts','qualificationPeer.ts','qualificationManifest.ts'].map(name=>({source:relative(repo,resolve(fixture,'convex',name))}))]){const text=readFileSync(resolve(repo,row.source),'utf8'),ast=ts.createSourceFile(row.source,text,ts.ScriptTarget.Latest,true);const aliases=new Map();
 for(const node of ast.statements)if(ts.isImportDeclaration(node)&&ts.isStringLiteral(node.moduleSpecifier)){const spec=node.moduleSpecifier.text;imports.push({from:row.source,specifier:spec});const clause=node.importClause?.namedBindings;if(clause&&ts.isNamedImports(clause))for(const element of clause.elements)aliases.set(element.name.text,element.propertyName?.text??element.name.text);}
 const walk=node=>{if(ts.isCallExpression(node)){const called=node.expression.getText(ast);if(/(installDeploymentPolicy|provisionTenantPolicy|reconcileDeploymentLiability)/.test(node.getText(ast)))callers.push({file:row.source,call:called,line:ast.getLineAndCharacterOfPosition(node.pos).line+1});}ts.forEachChild(node,walk);};walk(ast);
 for(const node of ast.statements){if(!ts.isVariableStatement(node)||!node.modifiers?.some(m=>m.kind===ts.SyntaxKind.ExportKeyword))continue;for(const d of node.declarationList.declarations){if(!ts.isIdentifier(d.name)||!d.initializer||!ts.isCallExpression(d.initializer))continue;const expression=d.initializer.expression;if(!ts.isIdentifier(expression))continue;const builder=aliases.get(expression.text)??expression.text;if(!['query','mutation','action','internalQuery','internalMutation','internalAction','httpAction'].includes(builder))continue;if(builder==='httpAction')continue;registrations.push({path:row.source.split('/').at(-1).replace(/\.ts$/,'')+':'+d.name.text,type:builder.replace(/^internal/,'').toLowerCase(),visibility:builder.startsWith('internal')?'internal':'public',source:row.source,builder});}}
 }
 const modules=[...new Set(registrations.map(row=>row.source))];const entry=resolve(destination,'inventory-entry.ts');writeFileSync(entry,modules.map((p,i)=>`import * as m${i} from ${JSON.stringify(resolve(fixture,'convex',p.split('/').at(-1)))};`).join('\n')+`\nimport product from ${JSON.stringify(resolve(fixture,'convex/productionSchema.ts'))};\nimport composed from ${JSON.stringify(resolve(fixture,'convex/schema.ts'))};\nexport const modules=[${modules.map((_,i)=>'m'+i).join(',')}];export const productSchema=product.export();export const composedSchema=composed.export();\n`);
 const output=resolve(destination,'inventory-bundle.mjs');await build({entryPoints:[entry],bundle:true,platform:'node',format:'esm',outfile:output,packages:'external',logLevel:'silent'});const inspected=await import(pathToFileURL(output));
 for(const row of registrations){const module=inspected.modules[modules.indexOf(row.source)],value=module[row.path.split(':')[1]];if(!value)throw Error('Missing actual export');row.actualInternal=value.isInternal===true;row.actualPublic=value.isPublic===true;row.args=JSON.parse(value.exportArgs());row.returns=JSON.parse(value.exportReturns());if(row.actualInternal!==(row.visibility==='internal'))throw Error('Visibility mismatch');}
 const product=JSON.parse(inspected.productSchema),composed=JSON.parse(inspected.composedSchema);if(product.schemaValidation!==composed.schemaValidation)throw Error('Schema option mismatch');for(const table of product.tables){const same=composed.tables.find(t=>t.tableName===table.tableName);if(JSON.stringify(same)!==JSON.stringify(table))throw Error('Schema changed');}
 if(composed.tables.length!==product.tables.length+1||composed.tables.filter(t=>t.tableName==='qaAdmissionPeerEffects').length!==1)throw Error('Fixture table mismatch');
 const productCounts={tables:product.tables.length,indexes:product.tables.reduce((n,t)=>n+t.indexes.length,0),searchVector:product.tables.reduce((n,t)=>n+t.searchIndexes.length+t.vectorIndexes.length,0)};
 const result={version:1,registrations,imports,bootstrapCallers:callers,unknown,productCounts,productSchemaSha256:sha256(inspected.productSchema),composedSchemaSha256:sha256(inspected.composedSchema),fixtureAdditions:['schema.ts','qualificationOwned.ts','qualificationPeer.ts','qualificationManifest.ts','http.ts'],httpRoutes:[{path:'/qa/task04-peer/effect',method:'POST',auth:'fixture-secret',handler:'qualificationPeer:effect'}],excludedUnregisteredGateway:'convex-dev/runtimeGateway.ts (not copied, never invoked)',limitations:'AST plus actual export metadata; actual apiSpec/public auth NOT_RUN'};
 if(process.argv.includes('--verify')){if(JSON.stringify(JSON.parse(readFileSync(resolve(root,'registration-inventory.json'),'utf8')))!==JSON.stringify(result)||JSON.stringify(JSON.parse(readFileSync(resolve(root,'schema-evidence.json'),'utf8')))!==JSON.stringify({product,composed,productCounts}))throw Error('QA_INVENTORY_DRIFT');}else{exclusive(resolve(root,'registration-inventory.json'),result,false,8388608);exclusive(resolve(root,'schema-evidence.json'),{product,composed,productCounts},false,8388608);}return result;
}
if(process.argv[1]?.endsWith('inventory.mjs'))await inventory(resolve(repo,'work/resume/task04-native-admission-fixture-c1'));
