/** Credential-free harness tests. No target/key/env/service/model/native QA execution. */
import {randomUUID} from 'node:crypto';
import assert from 'node:assert/strict';import test from 'node:test';import {readFileSync,lstatSync,writeFileSync,symlinkSync,linkSync,mkdirSync} from 'node:fs';import {resolve} from 'node:path';import {build} from 'esbuild';import {pathToFileURL} from 'node:url';
import {root,repo,fixture,sha256,safeReceipt,exclusive,canonical,limits,validateTarget} from './guard.mjs';import {shape} from './driver.mjs';import {sample} from './arguments.mjs';import {definitions,canonical as modelCanonical,request} from './cases.mjs';import {ProcessOwner} from './process-owner.mjs';import {boundedBody} from './peer.mjs';
const scratch=resolve(repo,'work/resume/task04-native-admission-fixture-c1/offline-'+randomUUID());mkdirSync(scratch,{mode:0o700});const successes=[];
function check(name,fn){test(name,async()=>{await fn();successes.push(name);});}
check('declared exact copies and sole bootstrap divergence',()=>{const inventory=JSON.parse(readFileSync(resolve(root,'source-inventory.json')));let unequal=[];for(const row of inventory.files){const source=readFileSync(resolve(repo,row.source)),copy=readFileSync(resolve(root,row.copy));assert.equal(sha256(source),row.sha256);if(!source.equals(copy))unequal.push(row.source);}assert.deepEqual(unequal,['convex-dev/runtimeModelPolicyBootstrap.ts']);});
check('fixed synthetic root identity and deeply frozen graph; production root remains empty',async()=>{const entry=resolve(scratch,'bootstrap-entry.ts');writeFileSync(entry,`export * as synthetic from ${JSON.stringify(resolve(fixture,'convex/runtimeModelPolicyBootstrap.ts'))};export * as production from ${JSON.stringify(resolve(repo,'convex-dev/runtimeModelPolicyBootstrap.ts'))};export { DEFAULT_EMBEDDING_PROFILE as profile } from ${JSON.stringify(resolve(repo,'src/domain/profile.ts'))};`);const output=resolve(scratch,'bootstrap.mjs');await build({entryPoints:[entry],bundle:true,format:'esm',platform:'node',packages:'external',outfile:output,logLevel:'silent'});const loaded=await import(pathToFileURL(output)),m=loaded.synthetic.lookupDeploymentManifest('qa-task04-synthetic-v1',1);assert.ok(m);assert.equal(m.classification,'fixture-synthetic');assert.ok(Object.isFrozen(m));assert.ok(Object.isFrozen(m.qualifications[0].costBound));assert.equal(loaded.synthetic.isTrustedDeploymentManifest(m),true);assert.equal(loaded.synthetic.isTrustedDeploymentManifest({...m}),false);assert.equal(loaded.synthetic.lookupDeploymentManifest('qa-task04-synthetic-v1',2),undefined);assert.equal(loaded.production.lookupDeploymentManifest('qa-task04-synthetic-v1',1),undefined);assert.equal(loaded.production.isTrustedDeploymentManifest(m),false);if(!lstatSync(resolve(root,'profile.json'),{throwIfNoEntry:false}))exclusive(resolve(root,'profile.json'),loaded.profile,false);});
check('actual native registration inventory and full product schema preservation',()=>{const i=JSON.parse(readFileSync(resolve(root,'registration-inventory.json')));assert.equal(i.registrations.filter(r=>r.visibility==='public').length,200);assert.equal(i.registrations.filter(r=>r.source==='convex-dev/runtimeModelPolicy.ts').length,14);assert.ok(i.registrations.filter(r=>r.source==='convex-dev/runtimeModelPolicy.ts').every(r=>r.actualInternal&&!r.actualPublic));assert.deepEqual(i.productCounts,{tables:31,indexes:184,searchVector:8});const e=JSON.parse(readFileSync(resolve(root,'schema-evidence.json')));assert.equal(e.composed.tables.length,32);for(const row of e.product.tables)assert.deepEqual(e.composed.tables.find(x=>x.tableName===row.tableName),row);});
check('all200 public argument samples obey actual native validators without storage writes',()=>{const i=JSON.parse(readFileSync(resolve(root,'registration-inventory.json')));for(const row of i.registrations.filter(x=>x.visibility==='public')){const value=sample(row.args,{runId:'admission-'+ 'a'.repeat(32),tenantId:'synthetic-tenant',memorySpaceId:'synthetic-space',ids:{_storage:'valid-format-ID-required-at-native-gate'}});assert.equal(shape(value,row.args),true,row.path);}assert.equal(shape({a:2},{type:'object',value:{a:{fieldType:{type:'string'},optional:false}}}),false);assert.equal(shape({a:'ok',extra:1},{type:'object',value:{a:{fieldType:{type:'string'},optional:false}}}),false);});
check('receipt allowlist rejects arbitrary secret/data fields and illegal status',()=>{assert.throws(()=>safeReceipt({status:'PASS',token:'secret'}));assert.throws(()=>safeReceipt({status:'UNKNOWN'}));assert.throws(()=>safeReceipt({status:'PASS',counts:{x:-1}}));assert.throws(()=>safeReceipt({status:'PASS',failureClass:'Bearer secret'}));assert.equal(safeReceipt({status:'PASS',counts:{rpc:2},noEffect:true}).noEffect,true);});
check('exclusive receipt refuses overwrite and path guard rejects symlinks/hardlinks',()=>{const path=resolve(scratch,'receipt.json');exclusive(path,{status:'PASS'});const pre=sha256(readFileSync(path));assert.throws(()=>exclusive(path,{status:'FAIL'}));assert.equal(sha256(readFileSync(path)),pre);const link=resolve(scratch,'symlink.json');symlinkSync(path,link);assert.throws(()=>canonical(link,scratch));const hard=resolve(scratch,'hard.json');linkSync(path,hard);assert.throws(()=>canonical(path,scratch));});
check('target rejects historical/shared/selector-conflicted identities',()=>{const request=JSON.parse(readFileSync(resolve(root,'project-request.json'))),target={...request,requestSha256:sha256(JSON.stringify(request)),projectId:1,deploymentName:'synthetic-target-123',deploymentUrl:'https://synthetic-target-123.convex.cloud',active:true,retired:false,deleted:false,isolationVerified:true};const values={CONVEX_DEPLOY_KEY:'dev:synthetic-target-123|synthetic-only-no-credential',CONVEX_DEPLOYMENT:'dev:synthetic-target-123',CONVEX_URL:target.deploymentUrl};assert.equal(validateTarget(target,request,values).projectId,1);for(const patch of [{projectId:3138249},{sharedCiTarget:true},{retired:true},{isolationVerified:false}])assert.throws(()=>validateTarget({...target,...patch},request,values));assert.throws(()=>validateTarget(target,request,values,{CONVEX_URL:'wrong'}));});
check('bounded HTTP body refuses oversized response before parsing',async()=>{assert.equal(await boundedBody(new Response('abc'),3),'abc');await assert.rejects(()=>boundedBody(new Response('abcd'),3),/CEILING/);});
check('case discovery includes8 repairs,2 positives,embedding/result/fallback/conflicting receipts',()=>{assert.equal(new Set(definitions.map(x=>x[0])).size,definitions.length);for(const id of ['fallback-fresh-money','fallback-current-query-reserve','fallback-postreserve-revoke','fallback-postreserve-money','held-current-operation','held-current-run','held-current-tenant','held-current-concurrency','held-exact-cap','fallback-exact-cap','embedding-single-bound','private-byte-exact-bound','predispatch-compatible-fallback','known-settlement-race'])assert.ok(definitions.some(x=>x[0]===id));assert.ok(definitions.length+6<=limits.scenarios);assert.equal(Buffer.byteLength(modelCanonical({text:'x'.repeat(59989)})),60000);assert.equal(Buffer.byteLength(modelCanonical({text:'x'.repeat(59990)})),60001);assert.equal(request().options.maxRetries,0);});
check('owned process waits leader and verifies terminal process group',async()=>{const owner=new ProcessOwner();const result=await owner.run(['-e','process.stdout.write("owned-ok")'],{cwd:scratch,env:{PATH:process.env.PATH}},2000);assert.equal(result.code,0);assert.equal(result.stdout,'owned-ok');assert.equal(owner.records.size,0);assert.equal(owner.verifiedGroups,1);});
check('owned process timeout kills descendants and retains honest timeout evidence',async()=>{const owner=new ProcessOwner();const result=await owner.run(['-e','require("node:child_process").spawn(process.execPath,["-e","setInterval(()=>{},1000)"],{stdio:"inherit"});setInterval(()=>{},1000)'],{cwd:scratch,env:{PATH:process.env.PATH}},100);assert.equal(result.timedOut,true);assert.equal(owner.records.size,0);assert.equal(owner.verifiedGroups,1);});

check('all26 historical definitions and173+8 indexes unchanged against accepted before-image',async()=>{
 const before=readFileSync(resolve(repo,'_goals/convex-backend-runtime-2026-10-02/qa/task04-admission-implementation-c1/schema.ts.before.text'),'utf8');const output=resolve(scratch,'before-schema.mjs');
 await build({stdin:{contents:before,resolveDir:resolve(fixture,'convex'),sourcefile:'before-schema.ts',loader:'ts'},bundle:true,format:'esm',platform:'node',packages:'external',outfile:output,logLevel:'silent'});
 const loaded=await import(pathToFileURL(output)),old=JSON.parse(loaded.default.export()),now=JSON.parse(readFileSync(resolve(root,'schema-evidence.json'))).product;
 assert.equal(old.tables.length,26);assert.equal(old.tables.reduce((n,t)=>n+t.indexes.length,0),173);assert.equal(old.tables.reduce((n,t)=>n+t.searchIndexes.length+t.vectorIndexes.length,0),8);
 for(const t of old.tables)assert.deepEqual(now.tables.find(x=>x.tableName===t.tableName),t);assert.equal(old.schemaValidation,now.schemaValidation);
});
