/** Exact committed-ID tracking across cleanup and process loss; never overwrites prior receipts. */
import {readFileSync,readdirSync,openSync,closeSync,unlinkSync} from 'node:fs';import {resolve} from 'node:path';import {scratch,root,json,sha256,exclusive} from './guard.mjs';
export function track(refs,kind,operation){if(!['created','deleted'].includes(kind)||!Array.isArray(refs)||refs.length>320)throw Error('QA_OWNERSHIP');const budget=json(resolve(root,'cases.json')).budgets.cumulativeRows;
 for(const ref of refs){if(!ref||typeof ref.table!=='string'||!/^[a-zA-Z][a-zA-Z0-9]*$/.test(ref.table)||typeof ref.id!=='string'||ref.id.length>128)throw Error('QA_OWNERSHIP_REF');const digest=sha256(ref.table+':'+ref.id),path=resolve(scratch,'owned-'+kind+'-'+digest+'.json');try{exclusive(path,{operation,kind,table:ref.table,id:ref.id,observedAt:new Date().toISOString()});}catch(error){if(error.code!=='EEXIST')throw error;const old=json(path,scratch,true);if(old.operation!==operation||old.table!==ref.table||old.id!==ref.id)throw Error('QA_OWNERSHIP_COLLISION');}
 const count=readdirSync(scratch).filter(name=>name.startsWith('owned-'+kind+'-')).length;if(count>budget)throw Error('QA_CUMULATIVE_ROW_BUDGET');}
}
export function ownedSnapshot(rows,runId){const operationIds=new Set(rows.filter(x=>x.table==='runtimeModelOperations'&&x.row.tenantId?.startsWith(runId+'-')).map(x=>x.id));return rows.filter(x=>x.row.tenantId?.startsWith(runId+'-')||x.row.subject?.startsWith(runId+'-')||x.row.run===runId||x.row.root?.manifestId==='qa-task04-synthetic-v1'||x.table==='runtimeModelAttempts'&&operationIds.has(x.row.operationDocumentId)).map(x=>({table:x.table,id:x.id}));}

export function ownershipCounts(){const names=readdirSync(scratch);return {cumulativeCreatedRows:names.filter(n=>n.startsWith('owned-created-')).length,cumulativeDeletedRows:names.filter(n=>n.startsWith('owned-deleted-')).length};}
export async function allocateRows(scope,maximum,operation,shared=false){const plan=json(resolve(root,'cases.json'));const permitted=scope==='security'?15:scope==='fault'?40:scope==='empty'?12:plan.scenarios.find(row=>row.id===scope)?.maximumCommittedCreatedRows;if(maximum!==permitted||!Number.isSafeInteger(maximum))throw Error('QA_ROW_ALLOCATION');const lock=resolve(scratch,'row-allocation.lock'),deadline=Date.now()+12000;let fd;while(fd===undefined){try{fd=openSync(lock,'wx',0o600);}catch(error){if(error.code!=='EEXIST'||Date.now()>=deadline)throw Error('QA_ROW_LOCK');await new Promise(done=>setTimeout(done,10));}}try{const path=resolve(scratch,'row-allocation-'+sha256(scope)+'.json');const existing=readdirSync(scratch).filter(n=>n.startsWith('row-allocation-')).map(n=>json(resolve(scratch,n),scratch,true));const prior=existing.find(row=>row.scope===scope);if(prior){if(!shared||scope!=='fault'||prior.operation!==operation||prior.maximum!==maximum)throw Error('QA_REPEATED_SCENARIO');return;}if(existing.some(row=>row.operation!==operation)||existing.reduce((n,row)=>n+row.maximum,0)+maximum>plan.budgets.cumulativeRows)throw Error('QA_CUMULATIVE_ROW_BUDGET');exclusive(path,{operation,scope,maximum});}finally{closeSync(fd);unlinkSync(lock);}}
