import pathlib,json,subprocess,datetime,hashlib,concurrent.futures,os
R=pathlib.Path('/workspace/Project-Cortex');C=R/'work/resume/registry/candidate';H=R/'_goals/convex-backend-runtime-2026-10-02/qa/task03b2b1/history';Q=R/'_goals/convex-backend-runtime-2026-10-02/qa/task03b2b1-resume-cycle4';S=Q/'scripts';S.mkdir(exist_ok=True);raw=Q/'raw';raw.mkdir(exist_ok=True)
old='/workspace/Project-Cortex/work/backend-runtime/task03b2b1-checkout'
for name in ['registry','core']:
 j=json.loads((H/f'cycle3-final/independent/jest.{name}.json').read_text());j['rootDir']=str(C);j['cacheDirectory']=str(R/f'work/resume/registry/cache-{name}');j['transform']['^.+\\.(ts|js)$'][0]=str(C/'node_modules/ts-jest');(S/f'jest.{name}.json').write_text(json.dumps(j,indent=2)+'\n')
for name in ['registry','core']:
 j=json.loads((H/f'cycle3-final/independent/tsconfig.{name}.json').read_text());j=json.loads(json.dumps(j).replace(old,str(C)));(S/f'tsconfig.{name}.json').write_text(json.dumps(j,indent=2)+'\n')
probes=[('original-authority',H/'cycle1/independent/authority-probes.mts.text'),('original-native',H/'cycle1/independent/probes.mts.text'),('original-graph',H/'cycle1/independent/graph-boundary.mts.text'),('original-accessor',H/'cycle2-final/independent/accessor-probes.mts.text'),('original-stateful',H/'cycle2-final/independent/stateful-envelope-probes.mts.text'),('required-graph',H/'cycle2-final/candidate/qa/cycle2/graph-boundary.mts.text'),('required-accessor',H/'cycle3-final/candidate/qa/accessor-outcomes.mts.text'),('required-stateful',H/'cycle3-final/candidate/qa/stateful-outcomes.mts.text'),('required-admission',H/'cycle3-final/candidate/qa/admission-probes.mts.text'),('db-read-matrix',H/'cycle3-final/independent/independent-read-matrix.mts.text'),('identity-required',H/'cycle3-final/independent/identity-required-outcomes.mts.text'),('identity-observation',H/'cycle3-final/independent/identity-read-probe.mts.text')]
mapping=[]
for name,p in probes:
 t=p.read_text().replace(old,str(C))
 if name=='identity-required':
  a="entry.stage==='postInsert'||entry.stage==='optionalRead'&&code==='FORBIDDEN'?1:0";assert a in t;t=t.replace(a,"entry.stage==='postInsert'?1:0")
 dst=S/(name+'.mts');dst.write_text(t);mapping.append({'name':name,'preservedSource':str(p.relative_to(R)),'originalSha256':hashlib.sha256(p.read_bytes()).hexdigest(),'replay':str(dst.relative_to(R)),'changes':'absolute candidate path only'+('; pre-fix writer observation replaced by required zero pre-effect attempts (strictly stronger)' if name=='identity-required' else '')})
(Q/'replay-mapping.json').write_text(json.dumps(mapping,indent=2)+'\n')
def run(pair):
 name,cmd=pair;start=datetime.datetime.now(datetime.timezone.utc).isoformat();env=dict(os.environ,CONVEX_URL='http://127.0.0.1:1',NEXT_PUBLIC_CONVEX_URL='http://127.0.0.1:1');p=subprocess.run(cmd,cwd=C,env=env,capture_output=True,text=True);(raw/(name+'.stdout')).write_text(p.stdout);(raw/(name+'.stderr')).write_text(p.stderr);rec={'name':name,'command':cmd,'cwd':str(C),'utcStart':start,'utcEnd':datetime.datetime.now(datetime.timezone.utc).isoformat(),'exitCode':p.returncode};(raw/(name+'.command.json')).write_text(json.dumps(rec,indent=2)+'\n');print(name,p.returncode,flush=True);return rec
node='node';tsc=str(C/'node_modules/typescript/bin/tsc');eslint=str(C/'node_modules/eslint/bin/eslint.js');jest=str(C/'node_modules/jest/bin/jest.js');tsx=str(C/'node_modules/tsx/dist/cli.mjs')
checks=[('node-version',[node,'--version']),('backend-types',[node,tsc,'-p','convex-dev/tsconfig.json','--noEmit']),('scoped-types',[node,tsc,'-p',str(S/'tsconfig.registry.json'),'--noEmit']),('core-types',[node,tsc,'-p',str(S/'tsconfig.core.json'),'--noEmit']),('scoped-lint',[node,eslint,'convex-dev/runtimeRegistryAuth.ts','convex-dev/agents.ts','convex-dev/memorySpaces.ts','convex-dev/contexts.ts','convex-dev/schema.ts','tests/unit/runtimeRegistryAuth','--max-warnings','0']),('core-lint',[node,eslint,'convex-dev/runtimeAuth.ts','tests/unit/runtimeAuth','--max-warnings','0']),('discovery',[node,'--experimental-vm-modules',jest,'--config',str(S/'jest.registry.json'),'--listTests','--json','--runInBand']),('registry-tests',[node,'--experimental-vm-modules',jest,'--config',str(S/'jest.registry.json'),'--runInBand','--json','--outputFile',str(Q/'registry-tests.json')]),('core-tests',[node,'--experimental-vm-modules',jest,'--config',str(S/'jest.core.json'),'--runInBand','--json','--outputFile',str(Q/'core-tests.json')]),('root-types',[node,tsc,'--noEmit']),('root-lint-types',[node,tsc,'-p','tsconfig.lint.json','--noEmit']),('catalog',[node,'_goals/convex-backend-runtime-2026-10-02/qa/task03b2b1/inventory.mjs',str(Q/'catalog')])]
checks += [(name,[node,tsx,str(S/(name+'.mts'))]) for name,_ in probes]
with concurrent.futures.ThreadPoolExecutor(max_workers=3) as pool:receipts=list(pool.map(run,checks))
(Q/'commands.json').write_text(json.dumps(receipts,indent=2)+'\n')
